### PR TITLE
Templates for pull request and readme are added. Feel free to use

### PR DESCRIPTION
**Pull request by OlegAndrus12**
## Description

It would be great to use the same templates for pull requests and have README file more structured.

# Issues

[LFND-45](https://lohfinder.atlassian.net/browse/LFND-45) | Create a proper README and pull requests template for the project

## How Has This Been Tested?

It can be tests only from the main branch. Since templates are visible only when added to the master.

## Checklist:

- [x] Pull request name matches ticket name
- [x] Pull request description is not empty
- [x] My code responds to the latest guidelines (are u satisfied with what you have done?)

### CODE REVIEW

**Review by arihilmir — CHANGES_REQUESTED** [review]
Please, remove the fake text from README.md. It misleads readers of the repository.

**Review by ZhavoronkovN — APPROVED** [review]
I don't think it was a must at the moment and some sections (like installation) for sure should be done somewhere in future...
But it is nice to have, well done!

**Comment by OlegAndrus12** [comment]
@arihilmir deleted misleading text from README file

**Review by arihilmir — APPROVED** [review]
Great! Good job :)

**Comment by OlegAndrus12** [comment]
merging into master. Thanks for checking!

**Pull request merged**
